# стадии нашего pipeline. Для группировки jobs.
# Нужно помнить, что stages выполняются последовательно, а job параллельно.
stages:
  # укажем одну стадию с именем test
  - test

# создадим job с именем eslint
eslint:
  # добавим ее в стадию test
  stage: test
  # укажем переменные окружения. В отличие от GitHub, в GitLab
  # переменные окружения являются постоянными для всей job.
  variables:
    NODE_VERSION: 14.17.0
  # секция script описывает шаги
  script:
    # установка NVM
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    # установка Node.js
    - nvm install $NODE_VERSION
    # установка зависимостей
    - npm install
    # запуск ESLint
    - npm run lint

# создадим job с именем prettier
prettier:
  # добавим ее в стадию test
  stage: test
  # укажем переменные окружения. В отличие от GitHub, в GitLab
  # переменные окружения являются постоянными для всей job.
  variables:
    NODE_VERSION: 14.17.0
  # секция script описывает шаги
  script:
    # установка NVM
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    # установка Node.js
    - nvm install $NODE_VERSION
    # установка зависимостей
    - npm install
    # запуск Prettier
    - npm run check:format